---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparta-db-mongo-deployment
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:7.0.6
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage       # Updated to match PVC name
          mountPath: /data/db
        args:
        - --bind_ip_all  # Allow connections from other pods
      volumes:
      - name: mongo-storage       # Updated to match PVC name
        persistentVolumeClaim:
          claimName: mongo-pvc      # Reference to your PVC

