name: Run Python Script and Commit Changes

on:
  push:
    paths:
      - '**/*.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'  # Specify the Python version you want to use

    - name: Run Python Script
      run: |
        generate_readme_contents_table.py  # Replace this with the actual name of your Python script that edits the README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Automated update to README.md after .md file change"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
